fixed lint errors

diff --git a/src/commands/checktoken.yml b/src/commands/checktoken.yml
--- a/src/commands/checktoken.yml
+++ b/src/commands/checktoken.yml
@@ -7,12 +7,9 @@ steps:
         #!/bin/bash -eo pipefail
         if [[ -z "${GITHUB_TOKEN}" ]]; then
           echo "ERROR: Missing environment variable GITHUB_TOKEN" >&2
-          if [[ -n "You have not stored a GitHub API token. A token is required to create a pull request.
-        " ]]; then
-            echo "You have not stored a GitHub API token. A token is required to create a pull request.
-        " >&2
+          if [[ -n "You have not stored a GitHub API token. A token is required to create a pull request." ]]; then
+            echo "You have not stored a GitHub API token. A token is required to create a pull request." >&2
           fi
-          
         else
           echo "Yes, GitHub is defined!"
         fi
